target-version = "py313"

extend-exclude = ["migrations/versions/*.py"]

[lint]

# View rules here: https://docs.astral.sh/ruff/rules/
select = ["ALL"]

ignore = [
    "D100",   # undocumented-public-module
    "D101",
    "D102",
    "D107",   # Missing docstring in __init__
    "D203",   # one-blank-line-before-class
    "D205",   # blank-line-after-summary
    "D211",   # blank-line-before-class
    "D212",   # multi-line-summary-first-line
    "D401",   # non-imperative-mood
    "TD",     # flake8-todos
    "FIX002", # Line contains TODO
    "D104",   # Missing docstring in public package
    "E501",   # line-too-long
    "COM812", # missing-trailing-comma
    "ISC001", # single-line-implicit-string-concatenation
    "D202",
    "ANN401",
]

# https://docs.astral.sh/ruff/settings/#lint_pydocstyle_convention
pydocstyle.convention = "pep257"

# Don't enforce certain rules on test files
[lint.per-file-ignores]
"tests/**" = [
    "D",       # Documentation related
    "S101",    # Use of assert
    "PLR2004", # Magic values
    "PLR0913", # Too many arguments
    "INP001",  # implicit-namespace-package
    "S105",    # hardcoded-password-string
    "SLF001",  # private member access
    "F403",    # undefined-local-with-import-star
    "F405",    # undefined-local-with-import-star-usage
]
